---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rca-scripts-%ORG%-pv
  labels:
    pv-name: rca-scripts-%ORG%-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: %EFSSERVER%
    path: /rca-scripts
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: %DOMAIN%
  name: rca-scripts-%ORG%-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  selector:
    matchLabels:
      pv-name: rca-scripts-%ORG%-pv
  resources:
    requests:
      storage: 10Mi

