apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: %DOMAIN%
  name: load-fabric-%ORG%
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
       app: hyperledger
       role: client
       org: %ORG%
       name: load-fabric-%ORG%
  template:
    metadata:
      labels:
       app: hyperledger
       role: client
       org: %ORG%
       name: load-fabric-%ORG%
    spec:
     containers:
       - name: load-fabric-%ORG%
         image: hyperledger/fabric-ca-tools:x86_64-1.1.0
         env:
          - name: GOPATH
            value: /opt/gopath
          - name: PEERORG
            value: %ORG%
         command: ["sh"]
         args:  ["-c", "/scripts/load-fabric.sh 2>&1; while true; do sleep 90; done;"]
         volumeMounts:
          - mountPath: /scripts
            name: rca-scripts
          - mountPath: /data
            name: rca-data
     volumes:
       - name: rca-scripts
         persistentVolumeClaim:
             claimName: rca-scripts-%ORG%-pvc
       - name: rca-data
         persistentVolumeClaim:
             claimName: rca-data-%ORG%-pvc
