apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: %DOMAIN%
  name: channel-artifacts
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
       app: hyperledger
       role: orderer
       org: %ORG%
       name: channel-artifacts
  template:
    metadata:
      labels:
       app: hyperledger
       role: orderer
       org: %ORG%
       name: channel-artifacts
    spec:
     containers:
       - name: channel-artifacts
         image: hyperledger/fabric-ca-tools:x86_64-1.1.0
         command: ["sh"]
         args:  ["-c", "/scripts/gen-channel-artifacts.sh 2>&1; while true; do sleep 90; done;"]
         volumeMounts:
          - mountPath: /scripts
            name: rca-scripts
          - mountPath: /data
            name: rca-data
     volumes:
       - name: rca-scripts
         persistentVolumeClaim:
             claimName: rca-scripts-%ORG%-pvc
       - name: rca-data
         persistentVolumeClaim:
             claimName: rca-data-%ORG%-pvc
