---
apiVersion: v1
kind: Service
metadata:
  namespace: %DOMAIN%
  name: orderer%NUM%-%ORG%-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
 selector:
   app: hyperledger
   role: orderer
   org: %ORG%
   name: orderer%NUM%-%ORG%
 type: NodePort
 ports:
   - name: endpoint
     protocol: TCP
     port: 7050
     targetPort: 7050
 type: LoadBalancer