# Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: %DOMAIN%
  name: ica-%ORG%
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
       app: hyperledger
       role: ca
       org: %ORG%
       name: ica-%ORG%
  template:
    metadata:
      labels:
       app: hyperledger
       role: ca
       org: %ORG%
       name: ica-%ORG%
    spec:
     containers:
       - name: ica-%ORG%
         image: hyperledger/fabric-ca:x86_64-1.1.0
         env:
         - name:  FABRIC_CA_SERVER_HOME
           value: /etc/hyperledger/fabric-ca
         - name:  FABRIC_CA_SERVER_TLS_ENABLED
           value: "true"
         - name:  FABRIC_CA_SERVER_CA_NAME
           value: ica-%ORG%.%DOMAIN%
         - name:  FABRIC_CA_SERVER_CSR_HOSTS
           value: ica-%ORG%.%DOMAIN%
         - name:  FABRIC_CA_SERVER_DEBUG
           value: "true"
         - name:  BOOTSTRAP_USER_PASS
           value: ica-%ORG%-admin:ica-%ORG%-adminpw
         - name:  TARGET_CHAINFILE
           value: /data/%ORG%-ca-chain.pem
         - name:  FABRIC_ORGS
           value: %FABRICORGS%
         - name:  FABRIC_CA_SERVER_INTERMEDIATE_TLS_CERTFILES
           value: /data/%ORG%-ca-cert.pem
         - name:  PARENT_URL
           value: https://rca-%ORG%-admin:rca-%ORG%-adminpw@rca-%ORG%.%DOMAIN%:7054
         - name:  ORG
           value: %ORG%
         ports:
          - containerPort: 7054
         command: ["sh"]
         args:  ["-c", "/scripts/start-intermediate-ca.sh %ORG% 2>&1"]
         volumeMounts:
          - mountPath: /etc/hyperledger/fabric-ca
            name: ica
          - mountPath: /scripts
            name: rca-scripts
          - mountPath: /data
            name: rca-data
     volumes:
       - name: ica
         persistentVolumeClaim:
             claimName: ica-%ORG%-pvc
       - name: rca-scripts
         persistentVolumeClaim:
             claimName: rca-scripts-%ORG%-pvc
       - name: rca-data
         persistentVolumeClaim:
             claimName: rca-data-%ORG%-pvc

---
apiVersion: v1
kind: Service
metadata:
  namespace: %DOMAIN%
  name: ica-%ORG%
spec:
 selector:
   app: hyperledger
   role: ca
   org: %ORG%
   name: ica-%ORG%
 type: NodePort
 ports:
   - name: endpoint
     protocol: TCP
     port: 7054
     targetPort: 7054
     nodePort: %PORT%
